### ISSUE TITLE
Was wide string supported removed completely from the nextgen branch?

### ISSUE THREAD

**Issue by f3re** [jjensen/luaplus51-all#11]
I'm attempting to update an embedded luaplus system that uses wide strings and it would appear that all of the wide string functionality was removed? Is that correct or am I missing the replacement functionality somewhere else in the repo?

**Comment by jamplus** [comment]
It is gone.  It was too much of a pain to integrate into each Lua release, both bug fix updates and Lua 5.2, Lua 5.3, and LuaJIT.

**Comment by jjensen** [comment]
It is gone. It was too much of a pain to integrate into each Lua release, both bug fix updates and Lua 5.2, Lua 5.3, and LuaJIT.

**Comment by f3re** [comment]
Thanks for the reply, good to know
