### ISSUE TITLE
LuaRocks module?

### ISSUE THREAD

**Issue by Etiene** [jjensen/luaplus51-all#16]
Hello! I just saw your email on the Lua mailing list. First of all, congratulations on the project.

You mentioned there was a 3.0 release but I don't see anything on the "releases" tab here on github and furthermore there is no package on LuaRocks. 

Do you plan to release it on LuaRocks?

Thanks :)

**Comment by jjensen** [comment]
The Lua mailing list post was about JamPlus (http://jamplus.org), a build system that has Lua integration, not the LuaPlus distribution.

LuaPlus is not a Lua module and therefore not relevant to LuaRocks. Some of my other Lua modules could have rockspecs generated for them, but I don't use LuaRocks.

**Comment by Etiene** [comment]
I see! You can use LuaRocks for command line tools as well, not just libraries. Yea, maybe I confused this repo with jamplus! Not sure how I got redirected here. Sorry for the confusion and thanks for replying! :)
